version: 2
updates:
  # Version updates for npm packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      # Prefix for commit message
      prefix: '[npm]'
      prefix-dev: '[npm-dev]'
    assignees:
      - 'mitsuki31'
    reviewers:
      - 'mitsuki31'
    labels:
      - 'chore'
      - 'dependencies'
      - 'bot'

  # Version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      # Prefix for commit message
      prefix: '[gh-actions]'
    assignees:
      - 'mitsuki31'
    reviewers:
      - 'mitsuki31'
    labels:
      - 'chore'
      - 'bot'
