/**
 * @internal
 * @module    runtime/argparser
 * @author    Ryuu Mitsuki <https://github.com/mitsuki31>
 * @license   MIT
 * @since     5.0.0
 */

import util from 'node:util';
import Yargs from 'yargs';
import { hideBin } from 'yargs/helpers';

import { YTMP3_SYMBOL, type ProjectMetadata } from '#globals';
import { ArgumentParserError } from '#error';
import { style as $c, DefaultLogger, Logger, TerminalFormatter } from '#/utils';
import { isNumber } from '#/vendor/type-utils';
import { style } from '#/vendor/colors';
import { getGlob, hasSetup } from '#runtime/env';
import type { ResolvedYTMP3Config, ResolvedYTMP3ConfigWithDev } from '#/core/config';
import { exampleUsages, maxWidth, refineHelp, TITLES } from './cli_conf/misc';

type YargsError = Error & { yargsMessage?: string };
export interface ConsumedArgvResult {
  yargs: Yargs.Argv;
  argv: Extract<Yargs.Argv["argv"], { $0: string }>;
}
export interface ConsumeArgvOptions {
  /**
   * If set to `true`, the consumer function will return a promise.
   * @default false
   */
  async?: boolean;
  /**
   * If set to `true`, any error occurred while parsing the argv will be thrown.
   * Otherwise, will ignore the error and just log the error message.
   * @default false
   */
  throwError?: boolean;
}

const moduleExtensions = ['js'];
const projectMetadata = (getGlob('$__metadata__$') || {}) as Partial<ProjectMetadata>;

/**
 * Options for the [Yargs](https://yargs.js.org/) parser.
 *
 * @internal
 * @since    5.0.0
 * @see      {@link https://github.com/yargs/yargs-parser#configuration | Yargs Parser Configuration}
 */
export const parserConfig: Partial<Yargs.ParserConfigurationOptions> = {
  'short-option-groups': true,
  'dot-notation': true,
  'parse-positional-numbers': false,
  'boolean-negation': true,  // Add support for options negation
  'negation-prefix': 'no-',  // Standard negation prefix
  'combine-arrays': false,
  'duplicate-arguments-array': true,
  'flatten-duplicate-arrays': true,
  'greedy-arrays': true,  // Need to be set, as in v18 it is disabled by default
  'populate--': false,
  'unknown-options-as-args': false,
  'strip-aliased': false,
  'strip-dashed': false,
  'sort-commands': true
};

function printVersion(count: number): void {
  const metadata = projectMetadata as ProjectMetadata;

  if (isNumber(count) && count === 1) {
    process.stdout.write(TerminalFormatter.stripANSI(metadata.versionStr, process.stdout));
  } else if (isNumber(count) && count >= 2) {
    process.stdout.write(TerminalFormatter.stripANSI(metadata.versionStr, process.stdout));
    Object.entries(metadata.dependencies).forEach(([dep, ver], idx, deps) => {
      const str = `  ${
        style('GR', ((idx !== deps.length - 1) ? '├── ' : '└── '))
      }${style(['**', 'BG'], dep)} => v${(ver as string).replace(/^\^/, '')}\n`;
      process.stdout.write(TerminalFormatter.stripANSI(str, process.stdout));
    });
  }
}

/**
 * Consumes the parsed arguments from Yargs.
 *
 * This function can be called with a boolean option `async` which is set to `false` by default.
 * If `async` is set to `true`, this function will return a promise that resolves to an object
 * with two properties: `yargs` and `argv`. If `async` is set to `false`, this function will return
 * an object with two properties: `yargs` and `argv`.
 *
 * If any error is thrown while parsing the arguments with Yargs, this function will catch the error
 * and log it to the standard error and then set the exit code of the process to `1`. If the error has
 * `yargsMessage` property, it will be used to log the error message instead. Otherwise, the `message`
 * property of the error will be used.
 *
 * This function will only parse these miscellaneous options:
 * - `help`: Prints the help message that is generated by Yargs.
 * - `version`: Prints the version of the YTMP3 module.
 * - `copyright`: Prints the copyright information of the YTMP3 module.
 * - `printConfig`: Prints the currently used configuration of the YTMP3 module.
 * - `printConfigAll`: Prints the currently used configuration of the YTMP3 module,
 *                     including the developer options and the Innertube config.
 *
 * @param yargs - The Yargs instance that is used to parse the arguments.
 * @param options - The options to use.
 *
 * @returns An object with two properties: `yargs` and `argv`. If the `async` option is set to `true`,
 *          this function will return a promise that resolves to the corresponding object.
 *
 * @internal
 * @since    5.0.0
 */
export function consumeArgv(yargs: Yargs.Argv, options?: ConsumeArgvOptions): ConsumedArgvResult | undefined;
export function consumeArgv(
  yargs: Yargs.Argv,
  options: ConsumeArgvOptions & { async: true }
): Promise<ConsumedArgvResult | undefined>;
export function consumeArgv(
  yargs: Yargs.Argv,
  options?: ConsumeArgvOptions
): ConsumedArgvResult | Promise<ConsumedArgvResult | undefined> | undefined {
  if (!Object.keys(projectMetadata).length) return;
  const metadata = projectMetadata as ProjectMetadata;
  const { stripANSI } = TerminalFormatter;
  const { async = false, throwError = false } = options || {};

  type SyncArgv = Extract<Yargs.Argv["argv"], { $0: string }>;
  type KnownArgv = SyncArgv & {
    help?: boolean;
    version?: number;
    copyright?: boolean;
    printConfig?: boolean;
    printConfigAll?: boolean;
  };

  let argv = {} as KnownArgv | Promise<KnownArgv>;

  try {
    argv = async ? yargs.parse() : yargs.parseSync();
  } catch (err) {
    if (err instanceof Error) {
      const errFormat = $c(['BR'], `${metadata.scriptName}: [${err.name}] %s`);
      if ((err as YargsError).yargsMessage) {
        console.error(errFormat, stripANSI((err as YargsError).yargsMessage as string, process.stderr));
      } else {
        console.error(errFormat, stripANSI(err.message, process.stderr));
        console.error(`${metadata.scriptName}: See ${$c('BY', '--help')} for more information usage`);
      }
      process.exitCode = 1;  // Set exit code to 1
      if (throwError) throw err;  // Re-throw the error if the `throwError` is set
      return;
    }
  }

  const helpMsg = refineHelp(yargs, metadata);
  const parsedConfigAll = getGlob('__parsedConfig') as ResolvedYTMP3Config;
  const parsedConfig = { ...parsedConfigAll } as Partial<ResolvedYTMP3ConfigWithDev>;
  // Remove developer options and Innertube config
  delete parsedConfig.developer_options;
  delete parsedConfig.innertubeConfig;

  function _consume(argv: KnownArgv): KnownArgv {
    if (argv.help) {
      process.stdout.write(stripANSI(helpMsg, process.stdout));
    } else if (typeof argv?.version === 'number') {
      printVersion(argv.version);
    } else if (argv?.copyright) {
      process.stdout.write(stripANSI(metadata.copyright, process.stdout));
    } else if (argv?.printConfig) {
      process.stdout.write(stripANSI(util.inspect(parsedConfig,
        { showHidden: false, depth: null, colors: true }
      ), process.stdout));
    } else if (argv?.printConfigAll) {
      process.stdout.write(stripANSI(util.inspect(parsedConfigAll,
        { showHidden: true, depth: null, colors: true }
      ), process.stdout));
    }
    return argv;
  }

  if (async && argv instanceof Promise) {
    return new Promise((resolve, reject) => {
      argv
        .then((a) => {
          _consume(a);
          resolve({ yargs, argv: a } as ConsumedArgvResult);
        })
        .catch(reject)
    });
  }

  // ? Consume other arguments?

  _consume(argv as KnownArgv);
  return { yargs, argv } as ConsumedArgvResult;
}


/**
 * Runs the setup for the argument parser.
 *
 * This function initializes and configures the Yargs argument parser.
 * It checks if the setup has been completed, throws an error if not,
 * and builds the parser with specified configurations and commands.
 *
 * @param options - Options for the setup.
 * @param options.argv - The argument vector to parse.
 * @param options.logger - The logger instance for logging debug messages.
 *
 * @returns The result of consuming the parsed arguments.
 *
 * @throws {@link ArgumentParserError} If the program has not been run the necessary setups.
 *
 * @internal
 * @since    5.0.0
 */
export function runSetup(options?: ConsumeArgvOptions & {
  argv?: string[];
  logger?: Logger;
  modules?: Yargs.CommandModule[];
}) {
  const { logger } = options ?? {};
  let { argv } = options ?? {};

  // Use Yargs helper to strip first two elements (node executable and script path)
  argv ??= hideBin(process.argv);

  // TODO: Add support for different locales
  // const usedLocale = yargs.locale();

  // Ensure that the setup is completed, otherwise throw an error
  if (!hasSetup()) {
    throw new ArgumentParserError(
      'FATAL: Unable to setup the argument parser\n'
      + 'If you are developer and want to run the setup for this module '
      + 'please use `runSetupUnconditionally()` function instead\n'
    );
  }

  const metadata = { ...projectMetadata } as ProjectMetadata;

  // Log the start of the argument parser setup if logger is provided
  logger?.debug('Building up argument parser...');

  // Initialize Yargs instance with specified configurations
  const yargs = Yargs(argv)
    .scriptName(metadata.scriptName)
    .help(false)     // Disable default --help option
    .version(false)  // Disable default --version option
    .wrap(maxWidth)  // Set wrap at maximum terminal width
    .strict(true)    // Enable strict mode to enforce valid command inputs
    .recommendCommands() // Suggest commands if not recognized
    .updateStrings({
      'Commands:': TITLES.commands,
      'Positionals:': TITLES.positional,
      'Examples:': TITLES.examples
    })
    .parserConfiguration(parserConfig) // Apply custom parser configurations
    .fail((msg, err) => {
      // Handle parsing failures by throwing appropriate errors
      if (err) {
        const yargsError: YargsError = err;
        yargsError.yargsMessage = msg;
        throw yargsError;
      }
      throw new ArgumentParserError(msg);
    })
    .example(exampleUsages) // Provide example usages
  ;

  // Register all command modules
  if (Array.isArray(options?.modules)) {
    options.modules.forEach((mod) => yargs.command(mod));
  } else {
    logger?.debug('No command modules to register');
  }
  logger?.debug(`Registered ${$c('C', String(options?.modules?.length ?? 0))} command module(s).`);

  // Consume and return the parsed arguments
  return consumeArgv(yargs, { ...options });
}

/**
 * Runs the argument parser setup unconditionally with optionally run
 * setup log and setup metadata.
 *
 * @remarks
 * This function is intended to be used by developers. When using this function
 * to run the argparser setup, the `throwError` will always set to `true`,
 * ignoring any override from the options.
 *
 * @internal
 * @since    5.0.0
 */
export function runSetupUnconditionally(options?: Parameters<typeof runSetup>[0]) {
  DefaultLogger.warn('Running argument parser setup unconditionally...');

  let { logger } = options ?? {};
  const { argv } = options ?? {};

  logger ??= getGlob('logger', undefined);
  // Push the 'ts' extension to the `moduleExtensions` array
  // This is a workaround to make TypeScript files can be used when exec the module using `npx`
  moduleExtensions.push('ts');

  // ! Unconditionally setup the application
  // Without this, any setup init will failed
  if (!hasSetup()) {
    DefaultLogger.warn('Looks like the application has not been setup yet');
    Object.assign(globalThis, { [YTMP3_SYMBOL]: {} });
  }

  if (!logger) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const setupLog = require('./setups/functions/log').default;
    setupLog();  // Setup log
    logger = getGlob('logger');
  }
  if (!Object.keys(projectMetadata).length) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const setupMetadata = require('./setups/functions/metadata').default;
    setupMetadata({ logger: logger as Logger });  // Setup project metadata
    Object.assign(projectMetadata, getGlob('$__metadata__$') as ProjectMetadata);
  }
  if (logger?.levelStr === 'DEBUG') logger.line(40, logger.DEBUG_PREFIX);

  return runSetup({ ...options, argv, logger, throwError: true });
}
