/**
 * @internal
 * @module    runtime/cli_conf/misc
 * @author    Ryuu Mitsuki <https://github.com/mitsuki31>
 * @license   MIT
 * @since     5.0.0
 */

import { stripVTControlCharacters } from 'node:util';
import Yargs from 'yargs';

import { style, type ColorFormat } from '#colors';
import { useNoColor } from '#runtime/env';
import { captureStdoutSync } from '#/utils/diag';
import type { ProjectMetadata } from '#globals';
import { TerminalFormatter } from '#/utils/terminal';

let $c = style;
if (useNoColor()) {
  $c = (_format: ColorFormat | ColorFormat[], ...text: string[]) => text.join(' ');
} else {
  $c = (format: ColorFormat | ColorFormat[], ...text: string[]) => {
    return TerminalFormatter.stripANSI(style(format, ...text), process.stdout);
  };
}

/**
 * The maximum width of the terminal or `null` if the terminal is not TTY.
 * @internal
 * @since 5.0.0
 */
export const maxWidth = Math.max(process.stdout.columns, process.stderr.columns) || null;

/**
 * A list of titles used for Yargs-based argument parser.
 * @internal
 * @since 5.0.0
 */
export const TITLES = {
  main: $c(['BC'], `${"=".repeat((maxWidth || 80) / 20)}> ${$c('**', '[Main Options]')}`),
  audioConv: $c(['BC'], `${"=".repeat((maxWidth || 80) / 20)}> ${$c('**', '[Audio Converter Options]')}`),
  misc: $c(['BC'], `${"=".repeat((maxWidth || 80) / 20)}> ${$c('**', '[Miscellaneous Options]')}`),
  commands: $c(['BC'], `${"=".repeat((maxWidth || 80) / 20)}> ${$c('**', '[Commands]')}`),
  positional: $c(['BC'], `${"=".repeat((maxWidth || 80) / 20)}> ${$c('**', '[Positional Arguments]')}`),
  examples: $c(['BC'], `${"=".repeat((maxWidth || 80) / 20)}> ${$c('**', '[Examples]')}`)
} as const;

/**
 * A list of example usages for the application.
 * @internal
 * @since 5.0.0
 */
export const exampleUsages: readonly [string, string?][] = [
  ['$0 https://youtu.be/VIDEO_ID', 'Download audio from a single URL'],
  ['$0 https://youtu.be/VIDEO_ID -o /home/Music', 'Download audio and save it to "/home/Music"'],
  ['$0 -f myplaylist.txt', 'Download multiple audios from a file'],
  ['$0 https://youtu.be/VIDEO_ID -C -D', 'Download audio and convert it to MP3 format'],
];

/**
 * Refine the help text generated by Yargs.
 *
 * @remarks To get the project metadata, the application needs to be setup first.
 *
 * @param yargs - The Yargs instance.
 * @param projectMetadata - The project metadata.
 *
 * @returns The refined help text.
 *
 * @internal
 * @since 5.0.0
 */
export function refineHelp(yargs: Yargs.Argv, projectMetadata: ProjectMetadata) {
  const help = captureStdoutSync(() => yargs.showHelp("log"));
  const usage = help.split('\n')[0];  // Usage always at the first line
  const versionStrStripped = stripVTControlCharacters(projectMetadata.versionStr.trim().replace(/(\[|\])/g, ''));
  const banner = `${style(['**'], versionStrStripped)}\n${style('BC', '='.repeat(versionStrStripped.length))}`;

  return TerminalFormatter.stripANSI(
    `${banner}\n\nUsage: ${style(['Y'], usage)}\n${help.split('\n').slice(1).join('\n')}\n`,
    process.stdout
  );
}

export const help = {
  _: 'h',
  alias: ['?', 'help'],
  describe: 'Show the help message',
  type: 'boolean',
  group: TITLES.misc
} as const;

export const version = {
  _: 'V',
  alias: ['version'],
  describe: 'Show the version information (use `-VV` to show deps version)',
  type: 'count',
  group: TITLES.misc
} as const;

export const copyright = {
  _: 'copyright',
  describe: 'Show the copyright information',
  type: 'boolean',
  group: TITLES.misc
} as const;

export const printConfig = {
  _: 'print-config',
  alias: ['printConfig'],
  describe: 'Show the parsed configuration. Useful for debugging',
  type: 'boolean',
  group: TITLES.misc
} as const;
