/**
 * @module    utils/diag/parser
 * @author    Ryuu Mitsuki <https://github.com/mitsuki31>
 * @license   MIT
 * @since     5.0.0
 */

import { style } from '#colors';
import { isDebugMode } from '#runtime/env.js';
import { Logger } from '#utils/log/index.js';

/**
 * Parses the output of an `InnertubeError` and returns an object containing the class
 * names and definitions of the missing classes, as well as a verbose error message.
 *
 * The function takes the output of an `InnertubeError` as a string and uses regular
 * expressions to extract the names and definitions of the missing classes. The
 * returned object contains three properties:
 *
 * - `classNames`: An array of class names of the missing classes.
 * - `classDefinitions`: An array of the entire class definitions of the missing classes.
 * - `shortErrorMsg`: An array of the short error messages that can be used to
 *   display the error to the user.
 *
 * @param errorMsg - The full output of an `InnertubeError` as a string which
 *                   contains information about the missing classes.
 *                   The output is typically captured from standard error output.
 *
 * @returns  An object containing the class names and definitions of the missing
 *           classes, as well as a verbose error message.
 *
 * @internal
 * @since    5.0.0
 */
export function parseParserError(errorMsg: string) {
  const classRegex = /class\s+(\w+)(?:\s+extends\s+YTNode)?\s*{[\s\S]*?^\}/gm;
  const matches = [...errorMsg.matchAll(classRegex)];

  const classNames = matches.map(m => m[1]);
  const classDefinitions = matches.map(m => m[0]);

  const shortErrorMsg = [
    ...errorMsg.matchAll(/^\[YOUTUBEJS\]\[Parser\]:\s*InnertubeError:\s*(.+?)\s*not\s*found!?$/gm)
  ].map(m => m[0]);

  return { classNames, classDefinitions, shortErrorMsg };
}

/**
 * Prints a parser error in a human-readable format.
 *
 * This function takes a parser error string and a logger object as input,
 * and prints the error in a formatted way. If debug mode is disabled,
 * it only prints a short error message. Otherwise, it also prints
 * the class definition of missing parsers.
 *
 * @param parserError - The parser error to print.
 * @param log - The logger to use for printing the error.
 *
 * @internal
 * @since 5.0.0
 */
export function prettyPrintParserError(parserError: string, log: Logger): void {
  const { shortErrorMsg, classNames, classDefinitions } = parseParserError(parserError);
  if (classNames.length > 0) {
    if (!isDebugMode()) {
      // If isDebugMode() is disabled, print the short error message
      shortErrorMsg.forEach((msg, idx) => {
        log.error(msg.replace(classNames[idx], style(['bgGR', 'Y'], classNames[idx])));
      });
      if (log.levelStr !== 'NONE') {
        log.write('Do not worry for errors above, everything is handled :)\n', null);
      }
    } else {  // isDebugMode() enabled
      shortErrorMsg.forEach((msg, idx) => {
        log.error(msg.replace(classNames[idx], style(['bgGR', 'Y'], classNames[idx])));
        if (log.levelStr !== 'NONE') {
          console.error('This class is auto-generated by YouTube.js using JIT in the meantime.\n');
          console.error(style('Y', classDefinitions[idx]));
        }
      });
    }
  }
}
