/**
 * @module    utils/constants
 * @author    Ryuu Mitsuki <https://github.com/mitsuki31>
 * @license   MIT
 * @since     5.0.0
 */

import path from 'node:path';
import os from 'node:os';

/**
 * The root directory of the project.
 *
 * @internal
 * @since  1.0.0
 */
export const ROOTDIR = path.join(__dirname, '..', '..');

/**
 * The home directory path for the YTMP3-JS configuration and data files.
 *
 * This path is constructed by joining the user's home directory with the `'.ytmp3-js'` folder.
 * On POSIX systems, this will typically be `"/home/<USERNAME>/.ytmp3-js"`, while on Windows systems,
 * it will be `"C:\\Users\\<USERNAME>\\.ytmp3-js"`. For Termux Android, it will be
 * `"/data/data/com.termux/files/home/.ytmp3-js"`.
 *
 * @internal
 * @since    1.1.0
 */
export const YTMP3_HOMEDIR = path.join(os.homedir(), '.ytmp3-js');

/**
 * The cache directory for YTMP3-JS, relative to the YTMP3-JS home directory.
 *
 * This directory is used to store the cached data of CLI application.
 *
 * @internal
 * @since 5.0.0
 */
export const YTMP3_CACHEDIR = path.join(YTMP3_HOMEDIR, '.cache');

/**
 * The cache directory for fetched video information.
 *
 * @internal
 * @since 5.0.0
 */
export const YTMP3_VINFO_CACHEDIR = path.join(YTMP3_CACHEDIR, '_vInfoContent');

/**
 * The cache directory for Innertube ({@link https://github.com/LuanRT/YouTube.js | YouTube.js}).
 *
 * @internal
 * @since 5.0.0
 */
export const INNERTUBE_CACHEDIR = path.join(YTMP3_CACHEDIR, '_innertube');

/**
 * The directory for stub parser classes.
 *
 * This directory contains stub parser classes for InnerTube ({@link https://github.com/LuanRT/YouTube.js | YouTube.js}).
 * The classes are auto-generated by Innertube JIT in the meantime during the runtime.
 *
 * @internal
 * @since 5.0.0
 */
export const STUB_CLASSES_DIR = path.join(YTMP3_HOMEDIR, 'stubs');

/**
 * The log directory for error logs.
 *
 * Basically, the log directory is set to:
 *   - **POSIX**: `$HOME/.ytmp3-js/logs`
 *   - **Windows**: `%USERPROFILE%\.ytmp3-js\logs`
 *
 * @internal
 * @since  1.0.0
 */
export const LOGDIR = path.join(YTMP3_HOMEDIR, 'logs');

/**
 * Regex for illegal characters.
 *
 * @internal
 * @since    5.0.0
 */
export const ILLEGAL_CHAR_REGEX = /[<>:"/\\|?*]/g;
