/**
 * Build the YTMP3-JS' central file for setup functions dynamically
 */

/* global console:readonly */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { lsFiles } from 'lsfnd';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');
const setupsDir = path.join(rootDir, 'src', 'runtime', 'setups', 'functions');
const targetFile = path.join(setupsDir, '..', 'index.ts');

const headerFile = [
  '// ! WARNING: DO NOT EDIT THIS MODULE MANUALLY!',
  `// This module is auto-generated by "${path.relative(path.resolve(__dirname, '..'), __filename)}"`,
  '',  // A gap between header file and exports
];

async function build() {
  // Get the setup files
  const setupFiles = await lsFiles(setupsDir, {
    match: /\.(m|c)?(ts|js)$/,
    absolute: false,
    recursive: false,
    rootDir: path.dirname(setupsDir),  // Will relative to the parent directory
  });
  const resolvedSetupFiles = setupFiles.map(file => file.replace(/\.ts$/, '.js'));

  // Construct the function names for exports
  const functionNames = resolvedSetupFiles.map(file => {
    const name = file.split(path.sep).pop().split('.')[0];
    return `setup${name.replace(name.charAt(0), name.charAt(0).toUpperCase())}`;
  });

  // Build the module content
  const moduleContentList = [
    ...headerFile,
    // Exports
    ...functionNames.map((fn, index) => {
      return `export { default as ${fn} } from './${resolvedSetupFiles[index]}';`;
    })
  ]

  // Generate the module
  await fs.promises.writeFile(targetFile, moduleContentList.join('\n') + '\n', {
    encoding: 'utf-8',
    flag: 'w'
  });
  console.log(
    `Generated ${path.relative(rootDir, targetFile)} for modules:\n`
    + setupFiles.map(file => `> ${path.relative(rootDir, path.join(setupsDir, file))}`).join('\n')
  );
}

await build();
