name: Codecov Coverage

on:
  push:
    branches: [ "master" ]

jobs:
  coverage:
    name: ${{ matrix.os }} / Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ Ubuntu, Windows, macOS ]
        node-version: [ 20.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js / ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean install the project
      run: npm ci
    - name: Run coverage
      # Currently we only run coverage for unit tests
      run: npx nyc --reporter lcov --reporter text npm run test:unit
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        name: codecov-unittest
        fail_ci_if_error: true
        env_vars: os,node-version
        directory: './coverage'
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
