name: Dependabot Auto-merge
on:
  pull_request:

# Required to edit pull requests
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'  # Only if the actor is Dependabot
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge Dependabot PR
        # Auto-merge all Dependabot PRs with patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        # Approve and merge the PR
        run: |
          gh pr review --approve "$PR_URL"
          gh pr comment --body "@dependabot merge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
