name: ESLint

on:
  push:
    paths: [ "**/*.{cjs,mjs,js}" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Ubuntu / Node.js (22.x)
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js / 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Clean install the project
      run: npm ci
    - name: Lint the project
      run: npm run lint
