name: IRL Test

on:
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 6,12,18,0 * * *'
  workflow_dispatch:

jobs:
  irltest:
    name: ${{ matrix.os }} / Node ${{ matrix.node-ver }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-ver: [ 18.x, 20.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js / ${{ matrix.node-ver }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-ver }}
        cache: 'npm'
    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
      with:
        ffmpeg-version: release
        linking-type: static
        architecture: x64
        github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
    - name: Clean install the project
      run: npm ci
    - name: Run IRL Test
      run: >
        npm run test:irl
