name: IRL Test

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6,18 * * *'  # Every day at 06:00 and 18:00 (twice a day)
  workflow_dispatch:

jobs:
  irltest:
    name: IRL Test (${{ matrix.os }}, Node v${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 18.x, 20.x ]

    env:
      FFMPEG_VERSION: 7.0.2
      NODE_ENV: development

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js / ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    # Will always fetch from the artifact
    - name: Fetch FFmpeg from artifact
      if: always()
      id: dl-ffmpeg-artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ runner.os }}-ffmpeg-${{ env.FFMPEG_VERSION }}-${{ runner.arch }}
        path: ${{ runner.tool_cache }}/ffmpeg/${{ env.FFMPEG_VERSION }}/${{ runner.arch }}
      continue-on-error: true

    # Run this job only if the job above is failed or cancelled
    - name: Fetch FFmpeg from sources
      if: ${{ !success() || steps.dl-ffmpeg-artifact.outcome == 'failure' }}
      uses: FedericoCarboni/setup-ffmpeg@v3
      id: dl-ffmpeg
      with:
        ffmpeg-version: ${{ env.FFMPEG_VERSION }}
        architecture: x64

    - name: Clean install the project
      run: npm ci

    - name: Run IRL Test
      # FIXME: This test is only specific to conversion tests and should be fixed in the future.
      #        This is due to YouTube restricts download YouTube videos in cloud CI environments
      #        and bots automation, unless handled by proxies.
      run: npm run test:irl:no-dltest
