name: Unit Test

on:
  push:
    paths: [ "**/test/**/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unittest:
    name: ${{ matrix.os }} / Node ${{ matrix.node-ver }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-ver: [ 16.x, 18.x, 20.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js / ${{ matrix.node-ver }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-ver }}
        cache: 'npm'
    - name: Clean install the project
      run: npm ci
    - name: Run unit tests
      run: npm run test:unit
